cidade = str(input('Qual nome da cidade que nasceu? '))
cidade_tratado = (cidade.lower()).split()
cidade_final = ''.join(cidade_tratado)
print(('sãogonçalo') in cidade_final)
print (cidade_tratado)
